/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.Color;
import model.*;
import dao.*;

/**
 *
 * @author 2004s
 */
public class TelaRegistroBarbeiro extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaRegistroBarbeiro() {
        initComponents();
        setLocationRelativeTo(null);
        JPanelLogin.setBackground(new java.awt.Color(255, 255, 255, 230));
        centralizarPainel(JPanelLogin);
        btnRegistrar.setBorderColor(new Color(2, 84, 45));
    }

    private void centralizarPainel(JPanel painel) {
        int larguraJanela = getWidth();
        int alturaJanela = getHeight();

        int larguraPainel = painel.getWidth();
        int alturaPainel = painel.getHeight();

        int x = (larguraJanela - larguraPainel) / 2;
        int y = (alturaJanela - alturaPainel) / 2;

        painel.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JPanelLogin = new view.RoundedPanel();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtEmail = new view.RoundedTextField();
        btnRegistrar = new view.RoundedButton();
        jLabel3 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        txtNome = new view.RoundedTextField();
        txtCpf = new view.RoundedTextField();
        txtTelefone = new view.RoundedTextField();
        txtSenha = new view.RoundedPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        JPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        JPanelLogin.setMinimumSize(new java.awt.Dimension(450, 500));
        JPanelLogin.setOpaque(false);
        JPanelLogin.setPreferredSize(new java.awt.Dimension(500, 500));
        JPanelLogin.setLayout(new java.awt.GridBagLayout());

        lblLogin.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        lblLogin.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        JPanelLogin.add(lblLogin, gridBagConstraints);

        lblSenha.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        lblSenha.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        JPanelLogin.add(lblSenha, gridBagConstraints);

        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setMaximumSize(new java.awt.Dimension(90, 22));
        txtEmail.setMinimumSize(new java.awt.Dimension(90, 22));
        txtEmail.setPreferredSize(new java.awt.Dimension(90, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 171;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        JPanelLogin.add(txtEmail, gridBagConstraints);

        btnRegistrar.setBackground(new java.awt.Color(20, 174, 92));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setFont(new java.awt.Font("Sitka Heading", 0, 16)); // NOI18N
        btnRegistrar.setMaximumSize(new java.awt.Dimension(100, 35));
        btnRegistrar.setMinimumSize(new java.awt.Dimension(100, 35));
        btnRegistrar.setPreferredSize(new java.awt.Dimension(100, 35));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 162;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        JPanelLogin.add(btnRegistrar, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/Made with insMind-logo 1 (3).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 154, 0, 146);
        JPanelLogin.add(jLabel3, gridBagConstraints);

        lblNome.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        lblNome.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        JPanelLogin.add(lblNome, gridBagConstraints);

        lblTelefone.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        lblTelefone.setText("Telefone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        JPanelLogin.add(lblTelefone, gridBagConstraints);

        lblCpf.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        lblCpf.setText("CPF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        JPanelLogin.add(lblCpf, gridBagConstraints);

        txtNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNome.setMinimumSize(new java.awt.Dimension(90, 22));
        txtNome.setPreferredSize(new java.awt.Dimension(90, 22));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 171;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        JPanelLogin.add(txtNome, gridBagConstraints);

        txtCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpf.setMinimumSize(new java.awt.Dimension(90, 22));
        txtCpf.setPreferredSize(new java.awt.Dimension(90, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 171;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        JPanelLogin.add(txtCpf, gridBagConstraints);

        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefone.setMinimumSize(new java.awt.Dimension(90, 22));
        txtTelefone.setPreferredSize(new java.awt.Dimension(90, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 171;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        JPanelLogin.add(txtTelefone, gridBagConstraints);

        txtSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSenha.setMaximumSize(new java.awt.Dimension(90, 22));
        txtSenha.setMinimumSize(new java.awt.Dimension(90, 22));
        txtSenha.setPreferredSize(new java.awt.Dimension(90, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 171;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        JPanelLogin.add(txtSenha, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(JPanelLogin, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/e36db9cf-fa87-4523-97b4-b44f1780840a 1.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.gridheight = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (!validarRegistro()) {
            return;
        }

        String nome = txtNome.getText().trim();
        String email = txtEmail.getText().trim();
        String senha = txtSenha.getText().trim();
        String telefone = txtTelefone.getText().trim();
        String cpf = txtCpf.getText().trim();

        Cliente cliente = new Cliente(0, nome, email, senha, TipoUsuario.BARBEIRO);

        ClienteDAO clienteDAO = new ClienteDAO();
        int idCliente = clienteDAO.cadastrarBarbeiro(cliente);

        if (idCliente == -1) {
            JOptionPane.showMessageDialog(this, "Erro ao criar usuário.");
            return;
        }

        BarbeiroDAO barbeiroDAO = new BarbeiroDAO();
        if (!barbeiroDAO.cadastrar(idCliente, telefone, cpf)) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar barbeiro.");
            return;
        }

        JOptionPane.showMessageDialog(this, "Barbeiro cadastrado com sucesso!");
        dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * Valida os dados informados na tela de registro.
     *
     * @return true se os dados forem válidos, false caso contrário
     */
    private boolean validarRegistro() {
        String nome = txtNome.getText().trim();
        String email = txtEmail.getText().trim();
        String senha = String.valueOf(txtSenha.getPassword()).trim();
        String telefone = txtTelefone.getText().trim();
        String cpf = txtCpf.getText().trim();

        if (nome.isEmpty() || email.isEmpty() || senha.isEmpty() || telefone.isEmpty() || cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
            return false;
        }

        if (!email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "E-mail inválido.");
            return false;
        }

        if (senha.length() < 6) {
            JOptionPane.showMessageDialog(this, "A senha deve ter pelo menos 6 caracteres.");
            return false;
        }

        if (!telefone.matches("\\d{10,11}")) {
            JOptionPane.showMessageDialog(this, "Telefone inválido.");
            return false;
        }

        if (!cpf.matches("\\d{11}")) {
            JOptionPane.showMessageDialog(this, "CPF inválido.");
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroBarbeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroBarbeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroBarbeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroBarbeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistroBarbeiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelLogin;
    private view.RoundedButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
