/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.Color;
import model.*;
import dao.*;
import util.Sessao;

/**
 *
 * @author 2004s Tela de Login do usuário
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setLocationRelativeTo(null);
        JPanelLogin.setBackground(new java.awt.Color(255, 255, 255, 230));
        centralizarPainel(JPanelLogin);
        btnEntrar.setBorderColor(new Color(44, 44, 44));
        btnRegistrar.setBorderColor(new Color(2, 84, 45));

    }

    private void centralizarPainel(JPanel painel) {
        int larguraJanela = getWidth();
        int alturaJanela = getHeight();

        int larguraPainel = painel.getWidth();
        int alturaPainel = painel.getHeight();

        int x = (larguraJanela - larguraPainel) / 2;
        int y = (alturaJanela - alturaPainel) / 2;

        painel.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JPanelLogin = new view.RoundedPanel();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtEmail = new view.RoundedTextField();
        txtSenha = new view.RoundedPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnEntrar = new view.RoundedButton();
        btnRegistrar = new view.RoundedButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        JPanelLogin.setMinimumSize(new java.awt.Dimension(450, 500));
        JPanelLogin.setOpaque(false);
        JPanelLogin.setPreferredSize(new java.awt.Dimension(500, 500));
        JPanelLogin.setLayout(new java.awt.GridBagLayout());

        lblLogin.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        lblLogin.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        JPanelLogin.add(lblLogin, gridBagConstraints);

        lblSenha.setFont(new java.awt.Font("Sitka Heading", 1, 16)); // NOI18N
        lblSenha.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        JPanelLogin.add(lblSenha, gridBagConstraints);

        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setMaximumSize(new java.awt.Dimension(90, 22));
        txtEmail.setMinimumSize(new java.awt.Dimension(90, 22));
        txtEmail.setPreferredSize(new java.awt.Dimension(90, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 171;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        JPanelLogin.add(txtEmail, gridBagConstraints);

        txtSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSenha.setMaximumSize(new java.awt.Dimension(90, 22));
        txtSenha.setMinimumSize(new java.awt.Dimension(90, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 171;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        JPanelLogin.add(txtSenha, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel2.setText("LOGIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        JPanelLogin.add(jLabel2, gridBagConstraints);

        btnEntrar.setBackground(new java.awt.Color(44, 44, 44));
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setFont(new java.awt.Font("Sitka Heading", 0, 16)); // NOI18N
        btnEntrar.setMaximumSize(new java.awt.Dimension(100, 35));
        btnEntrar.setMinimumSize(new java.awt.Dimension(100, 35));
        btnEntrar.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 162;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        JPanelLogin.add(btnEntrar, gridBagConstraints);

        btnRegistrar.setBackground(new java.awt.Color(20, 174, 92));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setFont(new java.awt.Font("Sitka Heading", 0, 16)); // NOI18N
        btnRegistrar.setMaximumSize(new java.awt.Dimension(100, 35));
        btnRegistrar.setMinimumSize(new java.awt.Dimension(100, 35));
        btnRegistrar.setPreferredSize(new java.awt.Dimension(100, 35));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 162;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 50, 0);
        JPanelLogin.add(btnRegistrar, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/Made with insMind-logo 1 (3).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(28, 154, 0, 146);
        JPanelLogin.add(jLabel3, gridBagConstraints);

        getContentPane().add(JPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/e36db9cf-fa87-4523-97b4-b44f1780840a 1.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 694));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        TelaRegistro tela = new TelaRegistro();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if (!validarLogin()) {
            return;
        }

        String email = txtEmail.getText().trim();
        String senha = String.valueOf(txtSenha.getPassword()).trim();

        ClienteDAO clienteDAO = new ClienteDAO();
        Cliente cliente = clienteDAO.login(email, senha);

        if (cliente == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "E-mail ou senha inválidos.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (cliente.getTipoUsuario() == TipoUsuario.BARBEIRO) {

            BarbeiroDAO barbeiroDAO = new BarbeiroDAO();
            Barbeiro barbeiro = barbeiroDAO.buscarPorCliente(cliente.getId());

            if (barbeiro == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Erro ao carregar dados do barbeiro.",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            Sessao.loginBarbeiro(cliente, barbeiro);

        } else {
            Sessao.login(cliente);
        }

        JOptionPane.showMessageDialog(
                this,
                "Bem-vindo, " + cliente.getNome() + "!"
        );
        
        AgendamentoDAO dao = new AgendamentoDAO();

        if (dao.clienteTemAgendamentoHoje(cliente.getId())) {
            JOptionPane.showMessageDialog(
                    this,
                    "Você tem um agendamento para hoje!"
            );
        }
        TelaMenu tela = new TelaMenu();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * Verifica se dados estão preenchidos e valida dados
     *
     * @return true se os dados forem válidos, false se não forem.
     */
    private boolean validarLogin() {
        String email = txtEmail.getText().trim();
        String senha = String.valueOf(txtSenha.getPassword()).trim();

        if (email.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
            return false;
        }

        if (!email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "E-mail inválido.");
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelLogin;
    private view.RoundedButton btnEntrar;
    private view.RoundedButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
