/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import dao.*;
import util.Sessao;
import java.util.*;
import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author 2004s
 */
public class TelaHistorico extends javax.swing.JFrame {

    private final Color corAvaliarAtivo = new Color(20, 174, 92);
    private final Color corAvaliarInativo = new Color(180, 180, 180);
    private List<Integer> idsAgendamentos = new ArrayList<>();

    /**
     * Creates new form TelaHistorico
     *
     *
     *
     */
    public TelaHistorico() {
        initComponents();
        setLocationRelativeTo(null);
        carregarHistorico();
        atualizarEstadoBotaoAvaliar(false);

        if (Sessao.isBarbeiro() || Sessao.isGerente()) {
            btnConcluir.setVisible(true);
            btnAvaliar.setVisible(false);
        } else {
            btnConcluir.setVisible(false);
        }

        tblHistorico.getSelectionModel().addListSelectionListener(e -> {
            int linha = tblHistorico.getSelectedRow();

            if (linha == -1) {
                atualizarEstadoBotaoAvaliar(false);
                return;
            }

            String status = tblHistorico.getValueAt(linha, 3).toString();
            int idAgendamento = idsAgendamentos.get(linha);

            if (!status.equalsIgnoreCase("Concluído")) {
                atualizarEstadoBotaoAvaliar(false);
                return;
            }

            AvaliacaoDAO avaliacaoDAO = new AvaliacaoDAO();

            if (avaliacaoDAO.existeAvaliacaoParaAgendamento(idAgendamento)) {
                atualizarEstadoBotaoAvaliar(false);
                btnAvaliar.setToolTipText("Este agendamento já foi avaliado");
                return;
            }

            atualizarEstadoBotaoAvaliar(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        roundedPanel1 = new view.RoundedPanel();
        icon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorico = new javax.swing.JTable();
        btnCancelar = new view.RoundedButton();
        btnVoltar = new view.RoundedButton();
        cboxStatus = new javax.swing.JComboBox<>();
        btnConcluir = new view.RoundedButton();
        btnAvaliar = new view.RoundedButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setLayout(new java.awt.GridBagLayout());

        icon.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/Made with insMind-logo 1 (3).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        roundedPanel1.add(icon, gridBagConstraints);

        lblTitle.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        lblTitle.setText("Histórico de Agendamentos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        roundedPanel1.add(lblTitle, gridBagConstraints);

        tblHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Data", "Horário", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblHistorico);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 834;
        gridBagConstraints.ipady = 364;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 14, 19, 16);
        roundedPanel1.add(jScrollPane1, gridBagConstraints);

        btnCancelar.setBackground(new java.awt.Color(20, 174, 92));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR AGENDAMENTO");
        btnCancelar.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 140);
        roundedPanel1.add(btnCancelar, gridBagConstraints);

        btnVoltar.setBackground(new java.awt.Color(20, 174, 92));
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("< VOLTAR");
        btnVoltar.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        roundedPanel1.add(btnVoltar, gridBagConstraints);

        cboxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Agendado", "Cancelado", "Concluído" }));
        cboxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxStatusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        roundedPanel1.add(cboxStatus, gridBagConstraints);

        btnConcluir.setBackground(new java.awt.Color(20, 174, 92));
        btnConcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnConcluir.setText("CONCLUIR AGENDAMENTO");
        btnConcluir.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        roundedPanel1.add(btnConcluir, gridBagConstraints);

        btnAvaliar.setBackground(new java.awt.Color(20, 174, 92));
        btnAvaliar.setForeground(new java.awt.Color(255, 255, 255));
        btnAvaliar.setText("AVALIAR AGENDAMENTO");
        btnAvaliar.setEnabled(false);
        btnAvaliar.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        btnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        roundedPanel1.add(btnAvaliar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -436;
        gridBagConstraints.ipady = -446;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(roundedPanel1, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/e36db9cf-fa87-4523-97b4-b44f1780840a 1.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int linha = tblHistorico.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um agendamento.");
            return;
        }

        String status = tblHistorico.getValueAt(linha, 3).toString();

        if (status.equalsIgnoreCase("Cancelado")) {
            JOptionPane.showMessageDialog(this, "Este agendamento já está cancelado.");
            return;
        }

        int opcao = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente cancelar este agendamento?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (opcao == JOptionPane.YES_OPTION) {
            int idAgendamento = idsAgendamentos.get(linha);

            AgendamentoDAO dao = new AgendamentoDAO();
            dao.cancelarAgendamento(idAgendamento);

            carregarHistorico();
            JOptionPane.showMessageDialog(this, "Agendamento cancelado com sucesso.");
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaMenu tela = new TelaMenu();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cboxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxStatusActionPerformed
        carregarHistorico();
    }//GEN-LAST:event_cboxStatusActionPerformed

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        int linha = tblHistorico.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um agendamento.");
            return;
        }

        String status = tblHistorico.getValueAt(linha, 3).toString();

        if (!status.equalsIgnoreCase("Agendado")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Apenas agendamentos em aberto podem ser concluídos."
            );
            return;
        }

        int confirmar = JOptionPane.showConfirmDialog(
                this,
                "Deseja marcar este agendamento como concluído?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmar != JOptionPane.YES_OPTION) {
            return;
        }

        int idAgendamento = idsAgendamentos.get(linha);

        AgendamentoDAO agendamentoDAO = new AgendamentoDAO();
        ServicoDAO servicoDAO = new ServicoDAO();
        FidelidadeDAO fidelidadeDAO = new FidelidadeDAO();
        HistoricoPagamentoDAO pagamentoDAO = new HistoricoPagamentoDAO();

        int idCliente = agendamentoDAO.buscarIdClientePorAgendamento(idAgendamento);
        int idServico = agendamentoDAO.buscarIdServicoPorAgendamento(idAgendamento);

        double valorServico = servicoDAO.buscarValorPorId(idServico);
        int estrelasNecessarias = (int) Math.ceil(valorServico / 5.0);

        String[] opcoes = {
            "Dinheiro",
            "Cartão",
            "Pix",
            "Estrelas (Fidelidade)"
        };

        String formaPagamento = (String) JOptionPane.showInputDialog(
                this,
                "Selecione a forma de pagamento:",
                "Pagamento",
                JOptionPane.QUESTION_MESSAGE,
                null,
                opcoes,
                opcoes[0]
        );

        if (formaPagamento == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Pagamento cancelado. O agendamento não foi concluído."
            );
            return;
        }

        if (formaPagamento.equals("Estrelas (Fidelidade)")) {

            int saldo = fidelidadeDAO.getEstrelas(idCliente);

            if (saldo < estrelasNecessarias) {
                JOptionPane.showMessageDialog(
                        this,
                        "Estrelas insuficientes.\n"
                        + "Necessárias: " + estrelasNecessarias
                        + "\nDisponíveis: " + saldo
                );
                return;
            }

            int confirmarEstrelas = JOptionPane.showConfirmDialog(
                    this,
                    "Este serviço custa " + estrelasNecessarias + " estrelas.\n"
                    + "Deseja confirmar o pagamento?",
                    "Pagamento por Fidelidade",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmarEstrelas != JOptionPane.YES_OPTION) {
                return;
            }

            fidelidadeDAO.debitarEstrelas(idCliente, estrelasNecessarias);
        }

        pagamentoDAO.salvar(idAgendamento, formaPagamento);
        agendamentoDAO.concluirAgendamento(idAgendamento);
        fidelidadeDAO.adicionarEstrela(idCliente);

        carregarHistorico();

        JOptionPane.showMessageDialog(
                this,
                "Agendamento concluído e pagamento registrado com sucesso."
        );
    }//GEN-LAST:event_btnConcluirActionPerformed

    private void btnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliarActionPerformed
        int linha = tblHistorico.getSelectedRow();
        if (linha == -1) {
            return;
        }

        int idAgendamento = idsAgendamentos.get(linha);

        AvaliacaoDAO dao = new AvaliacaoDAO();
        if (dao.existeAvaliacaoParaAgendamento(idAgendamento)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Este agendamento já foi avaliado."
            );
            atualizarEstadoBotaoAvaliar(false);
            return;
        }

        JComboBox<Integer> cbNota = new JComboBox<>(
                new Integer[]{1, 2, 3, 4, 5}
        );
        JTextArea txtComentario = new JTextArea(5, 20);
        JScrollPane scroll = new JScrollPane(txtComentario);

        Object[] mensagem = {
            "Nota (1 a 5):", cbNota,
            "Comentário (opcional):", scroll
        };

        int opcao = JOptionPane.showConfirmDialog(
                this,
                mensagem,
                "Avaliar Atendimento",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (opcao != JOptionPane.OK_OPTION) {
            return;
        }

        int nota = (Integer) cbNota.getSelectedItem();
        String comentario = txtComentario.getText().trim();

        dao.salvarAvaliacao(idAgendamento, nota, comentario);

        JOptionPane.showMessageDialog(
                this,
                "Avaliação registrada com sucesso!"
        );
    }//GEN-LAST:event_btnAvaliarActionPerformed

    /**
     * usado para alterar cor durante disable do botao avaliar
     *
     * @param ativo
     */
    private void atualizarEstadoBotaoAvaliar(boolean ativo) {
        btnAvaliar.setEnabled(ativo);

        if (ativo) {
            btnAvaliar.setBackground(corAvaliarAtivo);
            btnAvaliar.setForeground(Color.WHITE);
            btnAvaliar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            btnAvaliar.setToolTipText("Avaliar atendimento");
        } else {
            btnAvaliar.setBackground(corAvaliarInativo);
            btnAvaliar.setForeground(Color.DARK_GRAY);
            btnAvaliar.setCursor(Cursor.getDefaultCursor());
            btnAvaliar.setToolTipText(
                    "Apenas agendamentos concluídos podem ser avaliados"
            );
        }
    }

    /**
     * Responsável por carregar dados da tabela de histórico de agendamentos.
     */
    private void carregarHistorico() {
        DefaultTableModel model = (DefaultTableModel) tblHistorico.getModel();
        model.setRowCount(0);

        AgendamentoDAO dao = new AgendamentoDAO();
        idsAgendamentos.clear();

        if (Sessao.isCliente()) {

            int idCliente = Sessao.getCliente().getId();

            for (Object[] linha : dao.listarPorCliente(idCliente)) {

                idsAgendamentos.add((Integer) linha[0]);

                model.addRow(new Object[]{
                    linha[1],
                    linha[2],
                    linha[3],
                    linha[4]
                });
            }

        } else if (Sessao.isBarbeiro()) {

            int idBarbeiro = Sessao.getBarbeiro().getId();

            for (Object[] linha : dao.listarPorBarbeiro(idBarbeiro)) {

                idsAgendamentos.add((Integer) linha[0]);

                model.addRow(new Object[]{
                    linha[1],
                    linha[2],
                    linha[3],
                    linha[4]
                });
            }
        } else if (Sessao.isGerente()) {
            for (Object[] linha : dao.listarParaGerente(0)) {
                idsAgendamentos.add((Integer) linha[0]);
                model.addRow(new Object[]{
                    linha[1],
                    linha[2],
                    linha[3],
                    linha[4]
                });
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgendamento().setVisible(true);
            }
        });
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgendamento().setVisible(true);
            }
        });
         */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.RoundedButton btnAvaliar;
    private view.RoundedButton btnCancelar;
    private view.RoundedButton btnConcluir;
    private view.RoundedButton btnVoltar;
    private javax.swing.JComboBox<String> cboxStatus;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private view.RoundedPanel roundedPanel1;
    private javax.swing.JTable tblHistorico;
    // End of variables declaration//GEN-END:variables
}
