/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Sessao;
import dao.*;

/**
 *
 * @author 2004s
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
        setLocationRelativeTo(null);
        carregarBarbeiros();
        carregarEstrelas();

        if (Sessao.isGerente()) {
            btnCadastrarBarbeiro.setVisible(true);
        } else {
            btnCadastrarBarbeiro.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        roundedPanel1 = new view.RoundedPanel();
        icon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarbeiros = new javax.swing.JTable();
        btnNovoAgendamento = new view.RoundedButton();
        btnHistoricoAgendamento = new view.RoundedButton();
        btnSair = new view.RoundedButton();
        btnCadastrarBarbeiro = new view.RoundedButton();
        panelEstrelas = new view.RoundedPanel();
        lblEstrelas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setLayout(new java.awt.GridBagLayout());

        icon.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/Made with insMind-logo 1 (3).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        roundedPanel1.add(icon, gridBagConstraints);

        lblTitle.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        lblTitle.setText("Lista de Barbeiros");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        roundedPanel1.add(lblTitle, gridBagConstraints);

        tblBarbeiros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Avaliação Média", "Avaliações"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBarbeiros);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 834;
        gridBagConstraints.ipady = 364;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 19, 10);
        roundedPanel1.add(jScrollPane1, gridBagConstraints);

        btnNovoAgendamento.setBackground(new java.awt.Color(20, 174, 92));
        btnNovoAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoAgendamento.setText("NOVO AGENDAMENTO");
        btnNovoAgendamento.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        btnNovoAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAgendamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 400);
        roundedPanel1.add(btnNovoAgendamento, gridBagConstraints);

        btnHistoricoAgendamento.setBackground(new java.awt.Color(20, 174, 92));
        btnHistoricoAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoricoAgendamento.setText("HISTÓRICO DE AGENDAMENTOS");
        btnHistoricoAgendamento.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        btnHistoricoAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoAgendamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 10, 10);
        roundedPanel1.add(btnHistoricoAgendamento, gridBagConstraints);

        btnSair.setBackground(new java.awt.Color(20, 174, 92));
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("< SAIR");
        btnSair.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        roundedPanel1.add(btnSair, gridBagConstraints);

        btnCadastrarBarbeiro.setBackground(new java.awt.Color(20, 174, 92));
        btnCadastrarBarbeiro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarBarbeiro.setText("CADASTRAR BARBEIRO");
        btnCadastrarBarbeiro.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        btnCadastrarBarbeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarBarbeiroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        roundedPanel1.add(btnCadastrarBarbeiro, gridBagConstraints);

        panelEstrelas.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        panelEstrelas.setLayout(new java.awt.GridBagLayout());

        lblEstrelas.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblEstrelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEstrelas.add(lblEstrelas, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        roundedPanel1.add(panelEstrelas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -436;
        gridBagConstraints.ipady = -446;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(roundedPanel1, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/e36db9cf-fa87-4523-97b4-b44f1780840a 1.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAgendamentoActionPerformed
        int linhaSelecionada = tblBarbeiros.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um barbeiro para continuar.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int idBarbeiro = (int) tblBarbeiros.getValueAt(linhaSelecionada, 0);
        String nomeBarbeiro = tblBarbeiros.getValueAt(linhaSelecionada, 1).toString();

        TelaAgendamento tela = new TelaAgendamento(idBarbeiro, nomeBarbeiro);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNovoAgendamentoActionPerformed

    private void btnHistoricoAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoAgendamentoActionPerformed
        TelaHistorico tela = new TelaHistorico();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistoricoAgendamentoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Sessao.logout();
        new TelaLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarBarbeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarBarbeiroActionPerformed
        TelaRegistroBarbeiro tela = new TelaRegistroBarbeiro();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarBarbeiroActionPerformed

    private void carregarBarbeiros() {
        DefaultTableModel model = (DefaultTableModel) tblBarbeiros.getModel();
        model.setRowCount(0);

        BarbeiroDAO dao = new BarbeiroDAO();

        for (Object[] b : dao.listar()) {
            double media = (double) b[2];
            int total = (int) b[3];

            model.addRow(new Object[]{
                b[0], // id
                b[1], // nome
                media == 0 ? "Sem avaliações" : "⭐ " + media,
                total
            });
        }
    }

    private void carregarEstrelas() {
        int idCliente = Sessao.getCliente().getId();

        FidelidadeDAO dao = new FidelidadeDAO();
        int total = dao.buscarTotalEstrelas(idCliente);

        lblEstrelas.setText("⭐ " + total);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.RoundedButton btnCadastrarBarbeiro;
    private view.RoundedButton btnHistoricoAgendamento;
    private view.RoundedButton btnNovoAgendamento;
    private view.RoundedButton btnSair;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstrelas;
    private javax.swing.JLabel lblTitle;
    private view.RoundedPanel panelEstrelas;
    private view.RoundedPanel roundedPanel1;
    private javax.swing.JTable tblBarbeiros;
    // End of variables declaration//GEN-END:variables
}
