/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import java.util.*;
import java.sql.Timestamp;
import util.Sessao;
import model.*;
import dao.*;

/**
 *
 * @author 2004s
 */
public class TelaAgendamento extends javax.swing.JFrame {

    private boolean ajustandoData = false;
    private int idBarbeiroSelecionado;
    private int idServicoSelecionado;
    String dataSelecionada = "2026-06-10";
    String horarioSelecionado = "09:00:00";
    private List<Servico> listaServicos = new ArrayList<>();

    /**
     * Creates new form TelaAgendamento
     *
     * @param idBarbeiro recebe id do barbeiro selecionado
     * @param nomeBarbeiro recebe nome do barbeiro selecionado
     */
    public TelaAgendamento(int idBarbeiro, String nomeBarbeiro) {
        initComponents();
        setLocationRelativeTo(null);

        idBarbeiroSelecionado = idBarbeiro;

        JSpinner.DateEditor editor
                = new JSpinner.DateEditor(seletorData, "dd/MM/yyyy");
        seletorData.setEditor(editor);

        SpinnerDateModel model = (SpinnerDateModel) seletorData.getModel();
        model.setCalendarField(Calendar.DAY_OF_MONTH);

        Calendar hoje = Calendar.getInstance();
        hoje.set(Calendar.HOUR_OF_DAY, 0);
        hoje.set(Calendar.MINUTE, 0);
        hoje.set(Calendar.SECOND, 0);
        hoje.set(Calendar.MILLISECOND, 0);

        model.setStart(hoje.getTime());
        seletorData.setValue(hoje.getTime());

        Calendar c = Calendar.getInstance();
        c.setTime((Date) seletorData.getValue());

        int dia = c.get(Calendar.DAY_OF_WEEK);
        if (dia == Calendar.SATURDAY) {
            c.add(Calendar.DAY_OF_MONTH, 2);
            seletorData.setValue(c.getTime());
        } else if (dia == Calendar.SUNDAY) {
            c.add(Calendar.DAY_OF_MONTH, 1);
            seletorData.setValue(c.getTime());
        }

        seletorData.addChangeListener(e -> {

            if (ajustandoData) {
                return;
            }

            Calendar cal = Calendar.getInstance();
            cal.setTime((Date) seletorData.getValue());

            int diaSemana = cal.get(Calendar.DAY_OF_WEEK);

            if (diaSemana == Calendar.SATURDAY || diaSemana == Calendar.SUNDAY) {

                JOptionPane.showMessageDialog(
                        this,
                        "Não atendemos aos finais de semana."
                );

                ajustandoData = true;

                do {
                    cal.add(Calendar.DAY_OF_MONTH, 1);
                } while (cal.get(Calendar.DAY_OF_WEEK) == Calendar.SATURDAY
                        || cal.get(Calendar.DAY_OF_WEEK) == Calendar.SUNDAY);

                seletorData.setValue(cal.getTime());
                ajustandoData = false;
                return;
            }

            carregarHorarios();
        });

        carregarHorarios();
        carregarServicos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        roundedPanel1 = new view.RoundedPanel();
        icon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorarios = new javax.swing.JTable();
        btnAgendar = new view.RoundedButton();
        lblSelecionado = new javax.swing.JLabel();
        seletorData = new javax.swing.JSpinner();
        btnVoltar = new view.RoundedButton();
        cbServicos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(1316, 1011));
        roundedPanel1.setLayout(new java.awt.GridBagLayout());

        icon.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/Made with insMind-logo 1 (3).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        roundedPanel1.add(icon, gridBagConstraints);

        lblTitle.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        lblTitle.setText("Horários Disponíveis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        roundedPanel1.add(lblTitle, gridBagConstraints);

        tblHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Horário", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblHorarios);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 834;
        gridBagConstraints.ipady = 364;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 14, 19, 16);
        roundedPanel1.add(jScrollPane1, gridBagConstraints);

        btnAgendar.setBackground(new java.awt.Color(20, 174, 92));
        btnAgendar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendar.setText("AGENDAR");
        btnAgendar.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        roundedPanel1.add(btnAgendar, gridBagConstraints);

        lblSelecionado.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        lblSelecionado.setText("Barbeiro Selecionado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        roundedPanel1.add(lblSelecionado, gridBagConstraints);

        seletorData.setModel(new javax.swing.SpinnerDateModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        roundedPanel1.add(seletorData, gridBagConstraints);

        btnVoltar.setBackground(new java.awt.Color(20, 174, 92));
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("< VOLTAR");
        btnVoltar.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        roundedPanel1.add(btnVoltar, gridBagConstraints);

        cbServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbServicosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        roundedPanel1.add(cbServicos, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -436;
        gridBagConstraints.ipady = -421;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(roundedPanel1, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/e36db9cf-fa87-4523-97b4-b44f1780840a 1.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        int linha = tblHorarios.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um horário.");
            return;
        }

        String status = tblHorarios.getValueAt(linha, 1).toString();

        if (!status.equalsIgnoreCase("Disponível")) {
            JOptionPane.showMessageDialog(this, "Este horário não está disponível.");
            return;
        }

        int indice = cbServicos.getSelectedIndex();

        if (indice < 0 || indice >= listaServicos.size()) {
            JOptionPane.showMessageDialog(this, "Selecione um serviço.");
            return;
        }

        int idCliente = Sessao.getCliente().getId();
        int idBarbeiro = idBarbeiroSelecionado;

        Servico servicoSelecionado = listaServicos.get(indice);
        int idServico = servicoSelecionado.getId();

        String horarioSelecionado = tblHorarios.getValueAt(linha, 0).toString();

        java.util.Date data = (java.util.Date) seletorData.getValue();
        java.sql.Date dataSql = new java.sql.Date(data.getTime());

        Timestamp dataHora = Timestamp.valueOf(
                dataSql.toString() + " " + horarioSelecionado
        );

        AgendamentoDAO dao = new AgendamentoDAO();

        if (dao.salvarAgendamento(idCliente, idBarbeiro, idServico, dataHora)) {
            JOptionPane.showMessageDialog(this, "Agendamento realizado com sucesso!");
            TelaMenu tela = new TelaMenu();
            tela.setLocationRelativeTo(null);
            tela.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar agendamento.");
        }
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaMenu tela = new TelaMenu();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cbServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbServicosActionPerformed

    private void carregarHorarios() {
        DefaultTableModel model
                = (DefaultTableModel) tblHorarios.getModel();

        model.setRowCount(0);

        String[] horarios = {
            "09:00:00", "10:00:00", "11:00:00",
            "13:00:00", "14:00:00", "15:00:00",
            "16:00:00", "17:00:00"
        };

        java.util.Date utilDate = (java.util.Date) seletorData.getValue();
        java.sql.Date dataSelecionada = new java.sql.Date(utilDate.getTime());

        AgendamentoDAO dao = new AgendamentoDAO();
        List<String> ocupados
                = dao.listarHorariosOcupados(idBarbeiroSelecionado, dataSelecionada);

        for (String h : horarios) {
            String status = ocupados.contains(h)
                    ? "Ocupado"
                    : "Disponível";

            model.addRow(new Object[]{h, status});
        }
    }

    private void carregarServicos() {
        cbServicos.removeAllItems();
        listaServicos.clear();

        ServicoDAO dao = new ServicoDAO();
        List<Servico> servicos = dao.listarTodos();

        for (Servico s : servicos) {
            listaServicos.add(s);
            cbServicos.addItem(s.getNome());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgendamento().setVisible(true);
            }
        });
         */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.RoundedButton btnAgendar;
    private view.RoundedButton btnVoltar;
    private javax.swing.JComboBox<String> cbServicos;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelecionado;
    private javax.swing.JLabel lblTitle;
    private view.RoundedPanel roundedPanel1;
    private javax.swing.JSpinner seletorData;
    private javax.swing.JTable tblHorarios;
    // End of variables declaration//GEN-END:variables
}
